-- File generated by the BNF Converter (bnfc 2.9.4.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for PrintLatteFun.

module PrintLatteFun where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsLatteFun

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsLatteFun.Ident where
  prt _ (AbsLatteFun.Ident i) = doc $ showString i
instance Print (AbsLatteFun.Program' a) where
  prt i = \case
    AbsLatteFun.PProgram _ inits -> prPrec i 0 (concatD [prt 0 inits])

instance Print (AbsLatteFun.Init' a) where
  prt i = \case
    AbsLatteFun.IFnDef _ type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
    AbsLatteFun.IVarDef _ type_ id_ expr -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])

instance Print [AbsLatteFun.Init' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (AbsLatteFun.Arg' a) where
  prt i = \case
    AbsLatteFun.CopyArg _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
    AbsLatteFun.RefArg _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "ref"), prt 0 id_])

instance Print [AbsLatteFun.Arg' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsLatteFun.Block' a) where
  prt i = \case
    AbsLatteFun.SBlock _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsLatteFun.Stmt' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (AbsLatteFun.Stmt' a) where
  prt i = \case
    AbsLatteFun.SEmpty _ -> prPrec i 0 (concatD [doc (showString ";")])
    AbsLatteFun.SBStmt _ block -> prPrec i 0 (concatD [prt 0 block])
    AbsLatteFun.SDecl _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString ";")])
    AbsLatteFun.SInit _ init -> prPrec i 0 (concatD [prt 0 init])
    AbsLatteFun.SAss _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsLatteFun.SIncr _ id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    AbsLatteFun.SDecr _ id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])
    AbsLatteFun.SRet _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsLatteFun.SVRet _ -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsLatteFun.SCond _ expr block -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AbsLatteFun.SCondElse _ expr block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block1, doc (showString "else"), prt 0 block2])
    AbsLatteFun.SWhile _ expr block -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AbsLatteFun.SExp _ expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])

instance Print (AbsLatteFun.Type' a) where
  prt i = \case
    AbsLatteFun.TInt _ -> prPrec i 0 (concatD [doc (showString "int")])
    AbsLatteFun.TStr _ -> prPrec i 0 (concatD [doc (showString "string")])
    AbsLatteFun.TBool _ -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsLatteFun.TVoid _ -> prPrec i 0 (concatD [doc (showString "void")])
    AbsLatteFun.TFun _ targs type_ -> prPrec i 0 (concatD [doc (showString "["), doc (showString "("), prt 0 targs, doc (showString ")"), doc (showString "->"), prt 0 type_, doc (showString "]")])

instance Print (AbsLatteFun.TArg' a) where
  prt i = \case
    AbsLatteFun.TCopyArg _ type_ -> prPrec i 0 (concatD [prt 0 type_])
    AbsLatteFun.TRefArg _ type_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "ref")])

instance Print [AbsLatteFun.TArg' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsLatteFun.Type' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsLatteFun.Expr' a) where
  prt i = \case
    AbsLatteFun.EVar _ id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsLatteFun.ELitInt _ n -> prPrec i 6 (concatD [prt 0 n])
    AbsLatteFun.ELitTrue _ -> prPrec i 6 (concatD [doc (showString "true")])
    AbsLatteFun.ELitFalse _ -> prPrec i 6 (concatD [doc (showString "false")])
    AbsLatteFun.EApp _ id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsLatteFun.EAppLambda _ expr exprs -> prPrec i 6 (concatD [doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsLatteFun.EString _ str -> prPrec i 6 (concatD [printString str])
    AbsLatteFun.ENeg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsLatteFun.ENot _ expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsLatteFun.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsLatteFun.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsLatteFun.ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsLatteFun.EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsLatteFun.EOr _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
    AbsLatteFun.ELambdaExpr _ args type_ expr -> prPrec i 0 (concatD [doc (showString "lambda"), doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "->"), prt 0 type_, doc (showString "."), prt 0 expr])
    AbsLatteFun.ELambdaBlock _ args type_ block -> prPrec i 0 (concatD [doc (showString "lambda"), doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "->"), prt 0 type_, prt 0 block])

instance Print [AbsLatteFun.Expr' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsLatteFun.AddOp' a) where
  prt i = \case
    AbsLatteFun.OPlus _ -> prPrec i 0 (concatD [doc (showString "+")])
    AbsLatteFun.OMinus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (AbsLatteFun.MulOp' a) where
  prt i = \case
    AbsLatteFun.OTimes _ -> prPrec i 0 (concatD [doc (showString "*")])
    AbsLatteFun.ODiv _ -> prPrec i 0 (concatD [doc (showString "/")])
    AbsLatteFun.OMod _ -> prPrec i 0 (concatD [doc (showString "%")])

instance Print (AbsLatteFun.RelOp' a) where
  prt i = \case
    AbsLatteFun.OLTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    AbsLatteFun.OLE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsLatteFun.OGTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    AbsLatteFun.OGE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsLatteFun.OEQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    AbsLatteFun.ONE _ -> prPrec i 0 (concatD [doc (showString "!=")])
