-- File generated by the BNF Converter (bnfc 2.9.4.1).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language LatteFun.

module AbsLatteFun where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Program = PProgram [Init]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Init = IFnDef Type Ident [Arg] Block | IVarDef Type Ident Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Arg = CopyArg Type Ident | RefArg Type Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Block = SBlock [Stmt]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Stmt
    = SEmpty
    | SBStmt Block
    | SDecl Type Ident
    | SInit Init
    | SAss Ident Expr
    | SIncr Ident
    | SDecr Ident
    | SRet Expr
    | SVRet
    | SCond Expr Block
    | SCondElse Expr Block Block
    | SWhile Expr Block
    | SExp Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type = TInt | TStr | TBool | TVoid | TFun [Type] Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Expr
    = EVar Ident
    | ELitInt Integer
    | ELitTrue
    | ELitFalse
    | EApp Ident [Expr]
    | EAppLambda Expr [Expr]
    | EString String
    | ENeg Expr
    | ENot Expr
    | EMul Expr MulOp Expr
    | EAdd Expr AddOp Expr
    | ERel Expr RelOp Expr
    | EAnd Expr Expr
    | EOr Expr Expr
    | ELambdaExpr [Arg] Type Expr
    | ELambdaBlock [Arg] Type Block
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data AddOp = OPlus | OMinus
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data MulOp = OTimes | ODiv | OMod
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RelOp = OLTH | OLE | OGTH | OGE | OEQU | ONE
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

