-- File generated by the BNF Converter (bnfc 2.9.4.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for PrintLatteFun.

module PrintLatteFun where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsLatteFun

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsLatteFun.Ident where
  prt _ (AbsLatteFun.Ident i) = doc $ showString i
instance Print AbsLatteFun.Program where
  prt i = \case
    AbsLatteFun.PProgram inits -> prPrec i 0 (concatD [prt 0 inits])

instance Print AbsLatteFun.Init where
  prt i = \case
    AbsLatteFun.IFnDef type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
    AbsLatteFun.IVarDef type_ id_ expr -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])

instance Print [AbsLatteFun.Init] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsLatteFun.Arg where
  prt i = \case
    AbsLatteFun.CopyArg type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])
    AbsLatteFun.RefArg type_ id_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "ref"), prt 0 id_])

instance Print [AbsLatteFun.Arg] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsLatteFun.Block where
  prt i = \case
    AbsLatteFun.SBlock stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsLatteFun.Stmt] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsLatteFun.Stmt where
  prt i = \case
    AbsLatteFun.SEmpty -> prPrec i 0 (concatD [doc (showString ";")])
    AbsLatteFun.SBStmt block -> prPrec i 0 (concatD [prt 0 block])
    AbsLatteFun.SDecl type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString ";")])
    AbsLatteFun.SInit init -> prPrec i 0 (concatD [prt 0 init])
    AbsLatteFun.SAss id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsLatteFun.SIncr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    AbsLatteFun.SDecr id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])
    AbsLatteFun.SRet expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsLatteFun.SVRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsLatteFun.SCond expr block -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AbsLatteFun.SCondElse expr block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block1, doc (showString "else"), prt 0 block2])
    AbsLatteFun.SWhile expr block -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AbsLatteFun.SExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])

instance Print AbsLatteFun.Type where
  prt i = \case
    AbsLatteFun.TInt -> prPrec i 0 (concatD [doc (showString "int")])
    AbsLatteFun.TStr -> prPrec i 0 (concatD [doc (showString "string")])
    AbsLatteFun.TBool -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsLatteFun.TVoid -> prPrec i 0 (concatD [doc (showString "void")])
    AbsLatteFun.TFun types type_ -> prPrec i 0 (concatD [doc (showString "["), doc (showString "("), prt 0 types, doc (showString ")"), doc (showString "->"), prt 0 type_, doc (showString "]")])

instance Print [AbsLatteFun.Type] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsLatteFun.Expr where
  prt i = \case
    AbsLatteFun.EVar id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsLatteFun.ELitInt n -> prPrec i 6 (concatD [prt 0 n])
    AbsLatteFun.ELitTrue -> prPrec i 6 (concatD [doc (showString "true")])
    AbsLatteFun.ELitFalse -> prPrec i 6 (concatD [doc (showString "false")])
    AbsLatteFun.EApp id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsLatteFun.EAppLambda expr exprs -> prPrec i 6 (concatD [doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsLatteFun.EString str -> prPrec i 6 (concatD [printString str])
    AbsLatteFun.ENeg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsLatteFun.ENot expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsLatteFun.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsLatteFun.EAdd expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsLatteFun.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsLatteFun.EAnd expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsLatteFun.EOr expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
    AbsLatteFun.ELambdaExpr args type_ expr -> prPrec i 0 (concatD [doc (showString "lambda"), doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "->"), prt 0 type_, doc (showString "."), prt 0 expr])
    AbsLatteFun.ELambdaBlock args type_ block -> prPrec i 0 (concatD [doc (showString "lambda"), doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "->"), prt 0 type_, prt 0 block])

instance Print [AbsLatteFun.Expr] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsLatteFun.AddOp where
  prt i = \case
    AbsLatteFun.OPlus -> prPrec i 0 (concatD [doc (showString "+")])
    AbsLatteFun.OMinus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print AbsLatteFun.MulOp where
  prt i = \case
    AbsLatteFun.OTimes -> prPrec i 0 (concatD [doc (showString "*")])
    AbsLatteFun.ODiv -> prPrec i 0 (concatD [doc (showString "/")])
    AbsLatteFun.OMod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print AbsLatteFun.RelOp where
  prt i = \case
    AbsLatteFun.OLTH -> prPrec i 0 (concatD [doc (showString "<")])
    AbsLatteFun.OLE -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsLatteFun.OGTH -> prPrec i 0 (concatD [doc (showString ">")])
    AbsLatteFun.OGE -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsLatteFun.OEQU -> prPrec i 0 (concatD [doc (showString "==")])
    AbsLatteFun.ONE -> prPrec i 0 (concatD [doc (showString "!=")])
